# Generated by Django 5.0 on 2023-12-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.CharField(default='default_value', max_length=200),
        ),
    ]
