# Generated by Django 5.0 on 2023-12-08 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0002_book_page_count_alter_book_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
