# Generated by Django 5.0 on 2023-12-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0003_book_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
