# Generated by Django 5.0 on 2024-01-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0004_alter_book_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='content',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(max_length=3000),
        ),
    ]
