# Generated by Django 5.0 on 2024-01-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0005_alter_book_content_alter_review_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alienuser',
            name='bio',
            field=models.CharField(max_length=3000),
        ),
    ]
