# Generated by Django 5.0 on 2024-01-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0006_alter_alienuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
